name: test CI

on: # Event
  push:
    branches: [ master ] 
  pull_request:
    branches: [ master ]

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11 
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Test with Gradle
      run: ./gradlew test

    - name: Run Test Coverage
      run: ./gradlew jacocoTestReport

    - name: Generate JaCoCo Badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v2.5.0
      with:
        jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
        badges-directory: ./
        colors : '#4c1 #4c1 #4c1 #4c1 #fe7d37 #e05d44'
        intervals: 60 60 60 60 50 0

    - name: Log coverage percentage
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
        echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"


#     # add, commit and push to gh-pages
#     - name: Commit changes
#       uses: EndBug/add-and-commit@v9
#       with:
#         default_author: github_actions
#         new_branch: gh-pages
#         pull: '--rebase --autostash origin gh-pages'
#         message: 'Update report'
#         add: '*.svg'
        
    - name: Upload JaCoCo coverage report
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: build/reports/jacoco/test/html
        
     
     # download the doc files, most of which are generated above
    - name: Download Output Directory
      uses: actions/download-artifact@v2
      with:
        name: jacoco-report
#         path: report/

    # add, commit and push to gh-pages
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        new_branch: gh-pages
        pull: '--rebase --autostash origin gh-pages'
        message: 'Update report'
        add: '*.svg *.html'

        
